### ISSUE TITLE
Find Mean of the given array

### ISSUE THREAD

**Issue by UdhaikumarMohan** [SUREYAPRAGAASH09/Array-Problems#3]
according to your code, the output for finding mean will be integer right. But my doubt is what should we do when output seems to be a floating value.

example: Array=[9,0,1]

and its mean 10/3=3.33333

**Comment by SUREYAPRAGAASH09** [comment]
My Friend ,
        Tell me which question no you have doubt.
         Quesiton No is important for clearing your doubt

**Comment by UdhaikumarMohan** [comment]
I mentioned finding mean. If you want question number, here it is.
Question number: 8

**Comment by SUREYAPRAGAASH09** [comment]
Sorry My friend, I have not divided the sum of all the number in the array with its lenght of array elements. 
The output may or may not contains floating point values beause we are trying to divide the whole number by odd number will generate a floating point number.
Thank You for telling mistake in my code My friend ...
 happy Coding ..............

**Comment by SUREYAPRAGAASH09** [comment]
algorithm:
   1. find sum of all the elements in the array 
    2. divide the sum with lenght of the array using code form question 1
     3. return mean to the calling function   and this is my idea and if have any more though on how to solve the problem please tell me My friend ...
                                                     Happing Coding .....

**Comment by UdhaikumarMohan** [comment]
We will discuss more about in center. We have to concern floating points.

Happy Coding
