### ISSUE TITLE
This for question number 29

### ISSUE THREAD

**Issue by UdhaikumarMohan** [SUREYAPRAGAASH09/Array-Problems#4]
you did rotate the array by one bit. The code is more complex to understand me. Can you explain me how did you did that. I did it by using for loop, so it runs n times. But yours seems to be far good than mine.

Happy coding!!!!

**Comment by SUREYAPRAGAASH09** [comment]
My Approach : 

1. Remove the last element and place it on the temporary variable 
2. swap the temporary variable with all the element in the array 
3. so that we have achieved our goal 

                                               happy Coding ......

So if u have found any other approaches to solve the problem 29 please share with me also dude .

**Comment by SUREYAPRAGAASH09** [comment]
Dude i have made many changes in my repository and rename it 
New name : Unsorted-Array-Exercises
